// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskifyApi.DAL.Data;

#nullable disable

namespace WebApiTaskify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123182832_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "action", "action", new[] { "delete", "update", "create" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entity_type", "entity_type", new[] { "board", "list", "card" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiTaskify.Models.AuditLogs", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("action")
                        .HasMaxLength(10)
                        .HasColumnType("action");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("entityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("entityTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_title");

                    b.Property<int?>("entityType")
                        .HasColumnType("entity_type")
                        .HasColumnName("entity_type");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("orgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.Property<string>("userId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("userImage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_image");

                    b.Property<string>("userName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Boards", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("imageFullUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_full_url");

                    b.Property<string>("imageId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_id");

                    b.Property<string>("imageLinkHTML")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_link_html");

                    b.Property<string>("imageThumbUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_thumb_url");

                    b.Property<string>("imageUserName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_user_name");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("orgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Cards", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<Guid?>("listId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<int?>("order")
                        .HasColumnType("integer");

                    b.Property<bool?>("ready")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("timeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_end");

                    b.Property<DateTime?>("timeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_start");

                    b.Property<bool?>("timer")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Lists", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("boardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<int?>("order")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.OrgLimits", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("orgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.HasKey("id");

                    b.ToTable("org_limits", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.OrgSubscriptions", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("orgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("stripe_current_period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("stripe_customer_id")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("stripe_price_id")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("stripe_subscription_id")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_subscription_id");

                    b.HasKey("id");

                    b.ToTable("org_subscriptions", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Organizations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("website");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("createdUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("lastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("lastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
