// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskifyApi.DAL.Data;

#nullable disable

namespace WebApiTaskify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "action", "action", new[] { "delete", "update", "create" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entity_type", "entity_type", new[] { "board", "list", "card" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiTaskify.Models.AuditLogs", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Action")
                        .HasColumnType("action");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_title");

                    b.Property<int?>("EntityType")
                        .HasColumnType("entity_type")
                        .HasColumnName("entity_type");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("OrgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserImage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_image");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Boards", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("ImageFullUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_full_url");

                    b.Property<string>("ImageId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_id");

                    b.Property<string>("ImageLinkHTML")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_link_html");

                    b.Property<string>("ImageThumbUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_thumb_url");

                    b.Property<string>("ImageUserName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_user_name");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("OrgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Cards", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<string>("description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<Guid?>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<bool?>("ready")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("timeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_end");

                    b.Property<DateTime?>("timeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_start");

                    b.Property<bool?>("timer")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("ListId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Lists", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("BoardId");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.OrgLimits", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("OrgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.HasKey("id");

                    b.ToTable("org_limits", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.OrgSubscriptions", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StripeCurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stripe_current_period_end");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.Property<string>("OrgId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_id");

                    b.HasKey("id");

                    b.ToTable("org_subscriptions", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Organizations", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("website");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("LastModifyTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("LastModifyUser")
                        .HasColumnType("text")
                        .HasColumnName("last_modify_user");

                    b.HasKey("id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("WebApiTaskify.Models.Cards", b =>
                {
                    b.HasOne("WebApiTaskify.Models.Lists", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("List");
                });

            modelBuilder.Entity("WebApiTaskify.Models.Lists", b =>
                {
                    b.HasOne("WebApiTaskify.Models.Boards", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Board");
                });

            modelBuilder.Entity("WebApiTaskify.Models.Boards", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("WebApiTaskify.Models.Lists", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
